// Generated by CoffeeScript 1.12.6
(function() {
  var assert, scss_vars;

  assert = require('assert');

  scss_vars = require('../index');

  it('should fetch and parse variables', function() {
    var actual, expected, scss;
    scss = "$a: 123;\n\n$b: $a;\n\n$c: $a + 1;\n$d: ($a + 1);\n\n$button-colors:\n  (\n    'name': 'primary',\n    'params': (\n      'background': $a,\n      'background-hover': $aui-primary-button-background-hover,\n      'background-selected': $aui-primary-button-background-selected,\n      'border-selected': $aui-primary-button-border-selected,\n      'color': $aui-primary-button-color,\n      'color-hover': $aui-primary-button-color-hover,\n      'color-selected': $aui-primary-button-color-selected\n    ),\n    'last': 888\n  )";
    actual = scss_vars.getVariables(scss);
    expected = {
      a: 123,
      b: 123,
      c: 124,
      d: 124,
      'button-colors': {
        name: 'primary',
        params: {
          background: 123,
          'background-hover': void 0,
          'background-selected': void 0,
          'border-selected': void 0,
          color: void 0,
          'color-hover': void 0,
          'color-selected': void 0
        },
        last: 888
      }
    };
    return assert.deepEqual(actual, expected);
  });

}).call(this);

//# sourceMappingURL=test.js.map
